module.exports = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: ["class"],
  theme: {
    container: {
      center: true,
      padding: "1rem",
    },
    screens: {
      xs: "475px",
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1440px",
      "3xl": "1800px",
    },
    extend: {
      colors: {
        background: "#EFF2F5",
        foreground: "#171D28",
        card: "#FFFFFF",
        "card-foreground": "#171D28",
        popover: "#F8FAFC",
        "popover-foreground": "#171D28",
        primary: {
          DEFAULT: "#0D7C66",
          medium: "#12B891",
          light: "#D4F0EE",
        },
        "primary-foreground": "#E4EDF4",
        secondary: "#E4EDF4",
        "secondary-foreground": "#171D28",
        muted: "#DDE6EE",
        "muted-foreground": "#52665E",
        accent: "#E4EDF4",
        "accent-foreground": "#171D28",
        destructive: "#DC4C40",
        border: "#DDE2E6",
        input: "#DDE2E6",
        ring: "#0D7C66",
        sidebar: "#0B1A2B",
        "sidebar-foreground": "#CBD5E2",
        "sidebar-primary": "#0D7C66",
        "sidebar-primary-foreground": "#FFFFFF",
        "sidebar-accent": "rgba(255,255,255,0.09)",
        "sidebar-accent-foreground": "#CBD5E2",
        "sidebar-border": "rgba(255,255,255,0.10)",
        "sidebar-ring": "#12B891",
        success: "#0D7C66",
        warning: "#C07D20",
        info: "#2E6AA8",
      },
      borderRadius: {
        xl: "calc(var(--radius) + 4px)",
      },
    },
  },
  plugins: [],
}