module.exports = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: ["class"],
  theme: {
    container: {
      center: true,
      padding: "1rem",
    },
    screens: {
      xs: "475px",
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1440px",
      "3xl": "1800px",
    },
    extend: {
      colors: {
        white: "var(--card-solid)",
        background: "var(--background)",
        foreground: "var(--foreground)",
        card: "var(--card)",
        "card-bg": "var(--cardBg)",
        "card-solid": "var(--card-solid)",
        "card-foreground": "var(--card-foreground)",
        popover: "var(--popover)",
        "popover-foreground": "var(--popover-foreground)",
        primary: {
          DEFAULT: "var(--primary)",
          medium: "var(--primary-medium)",
          light: "var(--primary-light)",
        },
        "primary-foreground": "var(--primary-foreground)",
        secondary: "var(--secondary)",
        "secondary-foreground": "var(--secondary-foreground)",
        muted: "var(--muted)",
        "muted-foreground": "var(--muted-foreground)",
        accent: "var(--accent)",
        "accent-light": "var(--accent-light)",
        "accent-foreground": "var(--accent-foreground)",
        destructive: "var(--destructive)",
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        sidebar: "var(--sidebar)",
        "sidebar-bg": "var(--sidebarBg)",
        "sidebar-foreground": "var(--sidebar-foreground)",
        "sidebar-primary": "var(--sidebar-primary)",
        "sidebar-primary-foreground": "var(--sidebar-primary-foreground)",
        "sidebar-accent": "var(--sidebar-accent)",
        "sidebar-accent-foreground": "var(--sidebar-accent-foreground)",
        "sidebar-border": "var(--sidebar-border)",
        "sidebar-ring": "var(--sidebar-ring)",
        success: "var(--success)",
        "success-light": "var(--success-light)",
        warning: "var(--warning)",
        "warning-light": "var(--warning-light)",
        info: "var(--info)",
        danger: "var(--danger)",
        "danger-light": "var(--danger-light)",
        "text-primary": "var(--textPrimary)",
        "text-secondary": "var(--textSecondary)",
        "text-primary-light": "var(--textPrimary-light)",
        "page-bg-start": "var(--pageBgStart)",
        "page-bg-end": "var(--pageBgEnd)",
        "slate-900": "var(--foreground)",
        "slate-50": "var(--card-solid)",
        "slate-100": "var(--secondary)",
        "slate-200": "var(--border)",
        "slate-400": "var(--muted-foreground)",
        "slate-500": "var(--muted-foreground)",
        "slate-600": "var(--textSecondary)",
      },
      borderRadius: {
        xl: "calc(var(--radius) + 4px)",
      },
    },
  },
  plugins: [],
}
